SELECT 
	STATIONS.ID,
	STATIONS.NAME,
	STATIONS.CITY
FROM
	STATIONS
WHERE 
	STATIONS.ID IN (SELECT path.value 
			FROM CORRIDOR_STATIONS, 
			json_each(CORRIDOR_STATIONS.STATIONS) AS path
			WHERE CORRIDOR_STATIONS.ID = 10)