SELECT 
    STOPS.ID,
    STOPS.LINE_ID AS LINE,
    STOPS.STATION,
    STOPS.ARRIVAL_TIME,
    STOPS.DEPARTURE_TIME
FROM STOPS

INNER JOIN
    LINE
ON
    LINE.ID = STOPS.LINE_ID

WHERE LINE.ID = '05065'